In [23]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy import stats
%matplotlib inline

In [2]:
from google.colab import files 

arquivo = files.upload()



Saving diabetes.csv to diabetes.csv


In [4]:
df = pd.read_csv('diabetes.csv')

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [7]:
df.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [8]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [9]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
df['Pregnancies'].describe()

count    768.000000
mean       3.845052
std        3.369578
min        0.000000
25%        1.000000
50%        3.000000
75%        6.000000
max       17.000000
Name: Pregnancies, dtype: float64

In [11]:
df['Glucose'].describe()

count    768.000000
mean     120.894531
std       31.972618
min        0.000000
25%       99.000000
50%      117.000000
75%      140.250000
max      199.000000
Name: Glucose, dtype: float64

In [12]:
df.Glucose = df.Glucose.replace(0,df.Glucose.mean())

In [13]:
df.BloodPressure.describe()

count    768.000000
mean      69.105469
std       19.355807
min        0.000000
25%       62.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: BloodPressure, dtype: float64

In [ ]:
df.BloodPressure = df.BloodPressure.replace(0,df.BloodPressure.median())

In [15]:
df.BloodPressure.describe()

count    768.000000
mean      72.386719
std       12.096642
min       24.000000
25%       64.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: BloodPressure, dtype: float64

In [16]:
df.SkinThickness.describe()

count    768.000000
mean      20.536458
std       15.952218
min        0.000000
25%        0.000000
50%       23.000000
75%       32.000000
max       99.000000
Name: SkinThickness, dtype: float64

In [17]:
df.SkinThickness = df.SkinThickness.replace(0,df.SkinThickness.mean())

In [18]:
df.Insulin.describe()

count    768.000000
mean      79.799479
std      115.244002
min        0.000000
25%        0.000000
50%       30.500000
75%      127.250000
max      846.000000
Name: Insulin, dtype: float64

In [19]:
df.Insulin = df.Insulin.replace(0,df.Insulin.median())

In [20]:
df.BMI.describe()

count    768.000000
mean      31.992578
std        7.884160
min        0.000000
25%       27.300000
50%       32.000000
75%       36.600000
max       67.100000
Name: BMI, dtype: float64

In [21]:
df.BMI = df.BMI.replace(0,df.BMI.mean())

In [24]:
#verifica outliers
#verifica os outliers utilizando a função Z-scores
df_zs = df.drop(['Outcome'],1)
zs= np.abs(stats.zscore(df_zs))
print(zs)

[[0.63994726 0.86527574 0.03198993 ... 0.16725546 0.46849198 1.4259954 ]
 [0.84488505 1.20598931 0.5283186  ... 0.85153454 0.36506078 0.19067191]
 [1.23388019 2.01597855 0.69376149 ... 1.33182125 0.60439732 0.10558415]
 ...
 [0.3429808  0.02240928 0.03198993 ... 0.90975111 0.68519336 0.27575966]
 [0.84488505 0.14197684 1.02464727 ... 0.34213954 0.37110101 1.17073215]
 [0.84488505 0.94297153 0.19743282 ... 0.29847711 0.47378505 0.87137393]]


In [25]:
#Z-score
threshold = 3
print(np.where(zs > 3))

(array([  4,   8,  13,  18,  43,  45,  57,  58,  88, 106, 111, 120, 120,
       123, 125, 125, 153, 159, 177, 177, 186, 220, 228, 228, 247, 286,
       298, 330, 370, 370, 371, 392, 395, 409, 415, 445, 445, 445, 453,
       455, 459, 486, 549, 579, 584, 593, 597, 621, 645, 655, 666, 673,
       684, 691, 695, 753]), array([6, 4, 4, 2, 2, 6, 3, 6, 0, 2, 4, 3, 5, 7, 2, 5, 4, 0, 2, 5, 4, 4,
       4, 6, 4, 4, 0, 6, 4, 6, 6, 4, 6, 4, 4, 3, 5, 6, 7, 0, 7, 4, 2, 3,
       4, 6, 2, 6, 4, 4, 7, 5, 7, 2, 4, 4]))


In [31]:
#Filtro para retirar os valores com outliers
df_s_o = df[(zs < 3).all(axis=1)]

In [27]:
df

Pregnancies  Glucose  ...  Age  Outcome
0              6    148.0  ...   50        1
1              1     85.0  ...   31        0
2              8    183.0  ...   32        1
3              1     89.0  ...   21        0
4              0    137.0  ...   33        1
..           ...      ...  ...  ...      ...
763           10    101.0  ...   63        0
764            2    122.0  ...   27        0
765            5    121.0  ...   30        0
766            1    126.0  ...   47        1
767            1     93.0  ...   23        0

[768 rows x 9 columns]

In [32]:
df_s_o

Pregnancies  Glucose  ...  Age  Outcome
0              6    148.0  ...   50        1
1              1     85.0  ...   31        0
2              8    183.0  ...   32        1
3              1     89.0  ...   21        0
5              5    116.0  ...   30        0
..           ...      ...  ...  ...      ...
763           10    101.0  ...   63        0
764            2    122.0  ...   27        0
765            5    121.0  ...   30        0
766            1    126.0  ...   47        1
767            1     93.0  ...   23        0

[719 rows x 9 columns]

In [33]:
df_s_o.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   719.000000  719.000000  ...  719.000000  719.000000
mean      3.841446  120.042382  ...   32.922114    0.336579
std       3.279022   29.641984  ...   11.309623    0.472868
min       0.000000   44.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  115.000000  ...   29.000000    0.000000
75%       6.000000  138.000000  ...   40.000000    1.000000
max      13.000000  199.000000  ...   68.000000    1.000000

[8 rows x 9 columns]

In [37]:
df_s_o.to_csv('diabetes_clean.csv') 
files.download('diabetes_clean.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>